// Package pdf provides PDF post-processing operations for document artefact
// rendering: merging, page counting, heading page extraction, and Roman numeral
// page number stamping. It wraps pdfcpu to isolate PDF manipulation from the
// rest of the pipeline.
package pdf

import (
	"bytes"
	"fmt"
	"html"
	"os"
	"strings"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types"
)

// MergeFiles concatenates multiple PDFs into a single output file.
func MergeFiles(inFiles []string, outFile string) error {
	if len(inFiles) == 0 {
		return fmt.Errorf("merge: no input files")
	}
	return api.MergeCreateFile(inFiles, outFile, false, nil)
}

// PageCount returns the number of pages in a PDF file.
func PageCount(filePath string) (int, error) {
	return api.PageCountFile(filePath)
}

// HeadingPageMap reads a PDF generated by Chrome's PrintToPDF and extracts
// a mapping from heading anchor IDs to page numbers. It reads named
// destinations from the PDF structure.
//
// Chrome creates named destinations for heading IDs when the HTML contains
// link annotations (hidden <a href="#id"> elements). The destinations
// reference the page where each heading appears.
//
// If no named destinations are found, an empty map is returned (graceful
// degradation — the TOC will be rendered without page numbers).
func HeadingPageMap(filePath string, headingIDs []string) (map[string]int, error) {
	if len(headingIDs) == 0 {
		return nil, nil
	}

	ctx, err := api.ReadContextFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read pdf for heading extraction: %w", err)
	}

	// Build a lookup set for the heading IDs we care about.
	wanted := make(map[string]struct{}, len(headingIDs))
	for _, id := range headingIDs {
		wanted[id] = struct{}{}
	}

	result := make(map[string]int, len(headingIDs))

	// Strategy 1: Read from the Names tree (modern PDFs).
	if destsNode, ok := ctx.Names["Dests"]; ok && destsNode != nil {
		collectFromNameTree(ctx, destsNode, wanted, result)
	}

	// Strategy 2: Read from the old-style /Dests dictionary in the catalog.
	if len(result) < len(headingIDs) && ctx.Dests != nil {
		collectFromDestsDict(ctx, ctx.Dests, wanted, result)
	}

	// Strategy 3: Read link annotations (fallback for Chrome PDFs).
	if len(result) < len(headingIDs) {
		annotResult, err := HeadingPageMapFromAnnotations(filePath, headingIDs)
		if err == nil {
			for id, pageNr := range annotResult {
				if _, exists := result[id]; !exists {
					result[id] = pageNr
				}
			}
		}
	}

	return result, nil
}

// collectFromNameTree walks a pdfcpu name tree and collects destinations.
func collectFromNameTree(ctx *model.Context, node *model.Node, wanted map[string]struct{}, result map[string]int) {
	if node == nil {
		return
	}

	// Walk the leaf values of the name tree.
	for name, val := range node.D {
		if _, ok := wanted[name]; !ok {
			continue
		}
		if pageNr := resolveDestPageNr(ctx, val); pageNr > 0 {
			result[name] = pageNr
		}
	}

	// Recurse into children.
	for _, child := range node.Kids {
		collectFromNameTree(ctx, child, wanted, result)
	}
}

// collectFromDestsDict reads heading page numbers from the old-style /Dests dict.
func collectFromDestsDict(ctx *model.Context, dests types.Dict, wanted map[string]struct{}, result map[string]int) {
	for name, val := range dests {
		// Strip leading / from PDF name objects.
		cleanName := strings.TrimPrefix(name, "/")
		if _, ok := wanted[cleanName]; !ok {
			continue
		}
		if pageNr := resolveDestPageNr(ctx, val); pageNr > 0 {
			result[cleanName] = pageNr
		}
	}
}

// resolveDestPageNr extracts the page number from a destination value.
// A destination is typically an array: [pageRef /XYZ left top zoom].
func resolveDestPageNr(ctx *model.Context, val types.Object) int {
	// Dereference if indirect.
	val, _ = ctx.Dereference(val)
	if val == nil {
		return 0
	}

	// May be a dict with a /D key.
	if d, ok := val.(types.Dict); ok {
		if dArr, found := d.Find("D"); found {
			val, _ = ctx.Dereference(dArr)
		}
	}

	arr, ok := val.(types.Array)
	if !ok || len(arr) < 2 {
		return 0
	}

	// First element is the page reference (IndirectRef).
	pageRef, ok := arr[0].(types.IndirectRef)
	if !ok {
		return 0
	}

	// Resolve page reference to page number.
	pageNr, err := ctx.PageNumber(pageRef.ObjectNumber.Value())
	if err != nil || pageNr <= 0 {
		return 0
	}
	return pageNr
}

// toRoman converts an integer to a lowercase Roman numeral string.
func toRoman(n int) string {
	if n <= 0 {
		return ""
	}
	vals := []int{1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1}
	syms := []string{"m", "cm", "d", "cd", "c", "xc", "l", "xl", "x", "ix", "v", "iv", "i"}
	var b strings.Builder
	for i, v := range vals {
		for n >= v {
			b.WriteString(syms[i])
			n -= v
		}
	}
	return b.String()
}

// StampRomanPageNumbers replaces the page numbers in a PDF with lowercase
// Roman numerals. It generates a stamped copy in-place by writing to a temp
// file and renaming.
//
// The stamp is positioned at the bottom-right to match the default document
// footer layout. The dateStr is displayed at the bottom-left.
func StampRomanPageNumbers(filePath string, dateStr string) error {
	pageCount, err := PageCount(filePath)
	if err != nil {
		return fmt.Errorf("stamp roman: count pages: %w", err)
	}
	if pageCount == 0 {
		return nil
	}

	// Build per-page watermarks: one for each page with the Roman numeral.
	wms := make(map[int]*model.Watermark, pageCount)
	totalRoman := toRoman(pageCount)

	for i := 1; i <= pageCount; i++ {
		roman := toRoman(i)
		text := fmt.Sprintf("Page %s of %s", roman, totalRoman)
		desc := "font:Helvetica, points:9, pos:br, offset:-28 7, rotation:0, scale:1 abs, fillc:#666666"
		wm, err := api.TextWatermark(text, desc, true, false, types.POINTS)
		if err != nil {
			return fmt.Errorf("stamp roman page %d: create watermark: %w", i, err)
		}
		wms[i] = wm
	}

	// Write to temp file, then rename.
	tmpFile := filePath + ".tmp"
	if err := api.AddWatermarksMapFile(filePath, tmpFile, wms, nil); err != nil {
		os.Remove(tmpFile)
		return fmt.Errorf("stamp roman: apply watermarks: %w", err)
	}

	if err := os.Rename(tmpFile, filePath); err != nil {
		os.Remove(tmpFile)
		return fmt.Errorf("stamp roman: rename: %w", err)
	}

	return nil
}

// InjectHeadingLinks inserts hidden anchor links into the HTML before the
// closing </body> tag. These links cause Chrome's PrintToPDF to create
// internal link annotations and named destinations for each heading ID,
// which HeadingPageMap can then read to extract accurate page numbers.
func InjectHeadingLinks(htmlBytes []byte, headingIDs []string) []byte {
	if len(headingIDs) == 0 {
		return htmlBytes
	}

	var buf bytes.Buffer
	buf.WriteString(`<nav aria-hidden="true" style="position:absolute;left:-9999px;top:0;width:1px;height:1px;overflow:hidden;opacity:0;">`)
	for _, id := range headingIDs {
		buf.WriteString(`<a href="#`)
		buf.WriteString(html.EscapeString(id))
		buf.WriteString(`">.</a> `)
	}
	buf.WriteString(`</nav>`)

	// Insert before </body>.
	marker := []byte("</body>")
	idx := bytes.LastIndex(htmlBytes, marker)
	if idx < 0 {
		// No </body> found; append at the end.
		return append(htmlBytes, buf.Bytes()...)
	}

	result := make([]byte, 0, len(htmlBytes)+buf.Len())
	result = append(result, htmlBytes[:idx]...)
	result = append(result, buf.Bytes()...)
	result = append(result, htmlBytes[idx:]...)
	return result
}

// HeadingPageMapFromAnnotations reads link annotations from a PDF and
// extracts heading page numbers. It matches annotations to heading IDs
// by their order on the page where the hidden links were injected.
//
// This is the fallback strategy when named destinations are not available.
func HeadingPageMapFromAnnotations(filePath string, headingIDs []string) (map[string]int, error) {
	if len(headingIDs) == 0 {
		return nil, nil
	}

	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("open pdf for annotation reading: %w", err)
	}
	defer f.Close()

	annots, err := api.Annotations(f, []string{"1-"}, nil)
	if err != nil {
		return nil, fmt.Errorf("read annotations: %w", err)
	}

	result := make(map[string]int, len(headingIDs))

	// Walk all pages to find link annotations with internal destinations.
	for _, pgAnnots := range annots {
		linkAnnots, ok := pgAnnots[model.AnnLink]
		if !ok {
			continue
		}
		for _, renderer := range linkAnnots.Map {
			link, ok := renderer.(model.LinkAnnotation)
			if !ok {
				continue
			}
			if link.Dest == nil || link.Dest.PageNr <= 0 {
				continue
			}
			// Match by URI fragment: Chrome sometimes stores the fragment in URI.
			if link.URI != "" {
				id := strings.TrimPrefix(link.URI, "#")
				if _, found := result[id]; !found {
					result[id] = link.Dest.PageNr
				}
			}
		}
	}

	return result, nil
}
