apiVersion: bino.bi/v1alpha1
kind: LayoutPage
metadata:
  name: {{ .LayoutName }}
spec:
  children:
    - kind: Text
      spec:
        value: >-
          Welcome to {{ .ReportTitle }}!
          \${this.data['${{ .DataSourceName }}'][0].name} just shipped the latest KPI export.
        dataset: ${{ .DataSourceName }}
