package cli

import (
	"strings"
	"testing"

	"bino.bi/bino/internal/report/sqlgen"
	"bino.bi/bino/internal/schema"
)

// validateDoc renders a document and asserts it passes the embedded JSON schema.
func validateDoc(t *testing.T, doc *schema.Document) string {
	t.Helper()
	b, err := renderDataSourceManifest(doc)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if err := schema.Validate(b); err != nil {
		t.Fatalf("generated manifest failed schema.Validate:\n%s\nerror: %v", b, err)
	}
	return string(b)
}

func TestBuildDataSourceDocumentWizardFields(t *testing.T) {
	t.Run("CSV with extended options validates", func(t *testing.T) {
		eph := true
		data := DataSourceManifestData{
			Name:                "sales_csv",
			Type:                DataSourceTypeCSV,
			Path:                "data/sales.csv",
			CSVDelimiter:        ";",
			CSVThousands:        ".",
			CSVDecimalSeparator: ",",
			CSVDateFormat:       "%d/%m/%Y",
			Columns:             map[string]string{"amount": "DECIMAL(18,2)", "id": "BIGINT"},
			Ephemeral:           &eph,
		}
		got := validateDoc(t, buildDataSourceDocument(data))
		for _, want := range []string{"thousands:", "decimalSeparator:", "dateFormat:", "columns:", "ephemeral: true"} {
			if !strings.Contains(got, want) {
				t.Errorf("expected %q in output:\n%s", want, got)
			}
		}
		// columns and columnNames are mutually exclusive in the schema.
		if strings.Contains(got, "columnNames:") {
			t.Errorf("columnNames must not appear when Columns is set:\n%s", got)
		}
	})

	t.Run("Columns wins over CSVColumnNames", func(t *testing.T) {
		data := DataSourceManifestData{
			Name:           "c",
			Type:           DataSourceTypeCSV,
			Path:           "data/c.csv",
			Columns:        map[string]string{"a": "VARCHAR"},
			CSVColumnNames: []string{"x", "y"},
		}
		got := validateDoc(t, buildDataSourceDocument(data))
		if strings.Contains(got, "columnNames:") {
			t.Errorf("Columns must take precedence over CSVColumnNames:\n%s", got)
		}
	})

	t.Run("Excel with sheet validates", func(t *testing.T) {
		data := DataSourceManifestData{
			Name:  "book",
			Type:  DataSourceTypeExcel,
			Path:  "data/book.xlsx",
			Sheet: "Q2",
		}
		got := validateDoc(t, buildDataSourceDocument(data))
		if !strings.Contains(got, "sheet: Q2") {
			t.Errorf("expected sheet in output:\n%s", got)
		}
	})
}

// TestTypedSelectDataSetValidates verifies the wizard's end product: a DataSet
// whose query is generated by sqlgen.TypedSelect passes schema validation.
func TestTypedSelectDataSetValidates(t *testing.T) {
	cols := []sqlgen.Column{
		{Name: "id", Type: "BIGINT"},
		{Name: "Full Name", Type: "VARCHAR"},
		{Name: "amount", Type: "VARCHAR", TargetType: "DECIMAL(18,2)"},
	}
	query, _ := sqlgen.TypedSelect("sales_csv", cols, sqlgen.Options{Pretty: true})

	doc := buildDataSetDocument(DataSetManifestData{
		Name:         "sales",
		Query:        query,
		Dependencies: []string{"sales_csv"},
	})
	b, err := renderDataSourceManifest(doc)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if err := schema.Validate(b); err != nil {
		t.Fatalf("typed-select DataSet failed schema.Validate:\n%s\nerror: %v", b, err)
	}
	if !strings.Contains(string(b), "AS full_name") {
		t.Errorf("expected generated SQL in DataSet manifest:\n%s", b)
	}
}
