package cli

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"bino.bi/bino/internal/schema"
)

// TestBuildConnectionSecretDocument_SchemaValid verifies that the documents
// generated by `bino add connectionsecret` use the nested per-type auth block
// and validate against the embedded schema (regression for the flat/nested
// mismatch where generated secrets failed schema validation).
func TestBuildConnectionSecretDocument_SchemaValid(t *testing.T) {
	tests := []struct {
		name        string
		data        ConnectionSecretManifestData
		wantContain []string
	}{
		{
			name: "postgres",
			data: ConnectionSecretManifestData{
				Name: "pg_credentials", Type: ConnectionSecretTypePostgres, PasswordFromEnv: "POSTGRES_PASSWORD",
			},
			wantContain: []string{"type: postgres", "postgres:", "passwordFromEnv: POSTGRES_PASSWORD"},
		},
		{
			name: "mysql",
			data: ConnectionSecretManifestData{
				Name: "mysql_credentials", Type: ConnectionSecretTypeMySQL, PasswordFromEnv: "MYSQL_PASSWORD",
			},
			wantContain: []string{"type: mysql", "mysql:", "passwordFromEnv: MYSQL_PASSWORD"},
		},
		{
			name: "s3",
			data: ConnectionSecretManifestData{
				Name: "s3_credentials", Type: ConnectionSecretTypeS3, KeyID: "AKIA", SecretEnv: "AWS_SECRET_KEY",
			},
			wantContain: []string{"type: s3", "s3:", "keyId: AKIA", "secretFromEnv: AWS_SECRET_KEY"},
		},
		{
			name: "gcs",
			data: ConnectionSecretManifestData{
				Name: "gcs_credentials", Type: ConnectionSecretTypeGCS, KeyID: "GCSKEY", SecretEnv: "GCS_SECRET",
			},
			wantContain: []string{"type: gcs", "gcs:", "keyId: GCSKEY"},
		},
		{
			name: "r2",
			data: ConnectionSecretManifestData{
				Name: "r2_credentials", Type: ConnectionSecretTypeR2, KeyID: "R2KEY", SecretEnv: "R2_SECRET",
			},
			wantContain: []string{"type: r2", "r2:", "keyId: R2KEY"},
		},
		{
			name: "http",
			data: ConnectionSecretManifestData{
				Name: "http_credentials", Type: ConnectionSecretTypeHTTP, Username: "user", Password: "HTTP_PASSWORD",
			},
			wantContain: []string{"type: http", "http:", "username: user", "passwordFromEnv: HTTP_PASSWORD"},
		},
		{
			name: "azure",
			data: ConnectionSecretManifestData{
				Name: "azure_credentials", Type: ConnectionSecretTypeAzure, ConnectionString: "AZURE_CONN", AccountKey: "AZURE_KEY",
			},
			wantContain: []string{"type: azure", "azure:", "connectionStringFromEnv: AZURE_CONN"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := buildConnectionSecretDocument(tt.data)
			data, err := yaml.Marshal(doc)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			if err := schema.Validate(data); err != nil {
				t.Errorf("generated %s secret failed schema validation:\n%s\nerror: %v", tt.name, data, err)
			}
			for _, want := range tt.wantContain {
				if !strings.Contains(string(data), want) {
					t.Errorf("generated %s secret missing %q in:\n%s", tt.name, want, data)
				}
			}
		})
	}
}
