# typed: false
# frozen_string_literal: true

# Homebrew formula for bino CLI
# This file is auto-generated by CI. Do not edit manually.
class Bino < Formula
  desc "CLI tool for building pixel-perfect PDF reports from YAML manifests and SQL queries"
  homepage "https://cli.bino.bi"
  license "BSAL"
  version "VERSION_PLACEHOLDER"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/vVERSION_PLACEHOLDER/bino-cli_Darwin_arm64.tar.gz"
      sha256 "SHA256_DARWIN_ARM64_PLACEHOLDER"
    else
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/vVERSION_PLACEHOLDER/bino-cli_Darwin_x86_64.tar.gz"
      sha256 "SHA256_DARWIN_X86_64_PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bino-bi/bino-cli-releases/releases/download/vVERSION_PLACEHOLDER/bino-cli_Linux_x86_64.tar.gz"
      sha256 "SHA256_LINUX_X86_64_PLACEHOLDER"
    end
  end

  def install
    bin.install "bino"
  end

  def post_install
    system "#{bin}/bino", "setup"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bino version")
  end
end
