package updater

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"bino.bi/bino/internal/version"
)

// setBaseURL overrides the package-level baseURL for the duration of a test.
func setBaseURL(t *testing.T, url string) {
	t.Helper()
	old := baseURL
	baseURL = url
	t.Cleanup(func() { baseURL = old })
}

// setVersion overrides the build version for the duration of a test.
func setVersion(t *testing.T, v string) {
	t.Helper()
	old := version.Version
	version.Version = v
	t.Cleanup(func() { version.Version = old })
}

// writeTarGz builds an in-memory tar.gz archive with the given name → content entries.
func writeTarGz(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	gzw := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gzw)
	for name, content := range entries {
		hdr := &tar.Header{
			Name:     name,
			Mode:     0o755,
			Size:     int64(len(content)),
			Typeflag: tar.TypeReg,
		}
		if err := tw.WriteHeader(hdr); err != nil {
			t.Fatalf("write tar header %s: %v", name, err)
		}
		if _, err := tw.Write([]byte(content)); err != nil {
			t.Fatalf("write tar entry %s: %v", name, err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("close tar: %v", err)
	}
	if err := gzw.Close(); err != nil {
		t.Fatalf("close gzip: %v", err)
	}
	return buf.Bytes()
}

// writeZipBytes builds an in-memory zip archive with the given name → content entries.
func writeZipBytes(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	for name, content := range entries {
		fw, err := w.Create(name)
		if err != nil {
			t.Fatalf("create zip entry %s: %v", name, err)
		}
		if _, err := fw.Write([]byte(content)); err != nil {
			t.Fatalf("write zip entry %s: %v", name, err)
		}
	}
	if err := w.Close(); err != nil {
		t.Fatalf("close zip: %v", err)
	}
	return buf.Bytes()
}

// writeTestZip creates a zip file at path with the given name → content entries.
func writeTestZip(t *testing.T, path string, entries map[string]string) {
	t.Helper()
	if err := os.WriteFile(path, writeZipBytes(t, entries), 0o644); err != nil {
		t.Fatalf("write zip: %v", err)
	}
}

// writePlatformArchive builds the archive type the updater expects for the
// current platform: zip on Windows, tar.gz elsewhere.
func writePlatformArchive(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	if runtime.GOOS == "windows" {
		return writeZipBytes(t, entries)
	}
	return writeTarGz(t, entries)
}

func TestParseChecksums(t *testing.T) {
	validSum := strings.Repeat("ab", 32) // 64 hex chars

	tests := []struct {
		name  string
		input string
		want  map[string]string
	}{
		{
			name:  "single entry double space",
			input: validSum + "  bino-cli_Linux_x86_64.tar.gz\n",
			want:  map[string]string{"bino-cli_Linux_x86_64.tar.gz": validSum},
		},
		{
			name:  "single entry single space",
			input: validSum + " bino-cli_Windows_x86_64.zip\n",
			want:  map[string]string{"bino-cli_Windows_x86_64.zip": validSum},
		},
		{
			name: "skips comments and blank lines",
			input: "# generated by goreleaser\n\n" +
				validSum + "  asset.tar.gz\n",
			want: map[string]string{"asset.tar.gz": validSum},
		},
		{
			name:  "skips short checksum",
			input: "deadbeef  asset.tar.gz\n",
			want:  map[string]string{},
		},
		{
			name:  "skips malformed lines",
			input: "one\n" + validSum + " too many fields\n",
			want:  map[string]string{},
		},
		{
			name:  "empty input",
			input: "",
			want:  map[string]string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseChecksums(strings.NewReader(tt.input))
			if err != nil {
				t.Fatalf("parseChecksums() error = %v", err)
			}
			if len(got) != len(tt.want) {
				t.Fatalf("parseChecksums() = %v, want %v", got, tt.want)
			}
			for name, sum := range tt.want {
				if got[name] != sum {
					t.Errorf("checksum for %s = %q, want %q", name, got[name], sum)
				}
			}
		})
	}
}

func TestExtractBinaryFromTarGz(t *testing.T) {
	tests := []struct {
		name    string
		entries map[string]string
		want    string
		wantErr string
	}{
		{
			name:    "extracts bino",
			entries: map[string]string{"README.md": "docs", "bino": "binary-content"},
			want:    "binary-content",
		},
		{
			name:    "extracts bino.exe",
			entries: map[string]string{"bino.exe": "exe-content"},
			want:    "exe-content",
		},
		{
			name:    "binary missing",
			entries: map[string]string{"README.md": "docs"},
			wantErr: "bino binary not found",
		},
		{
			name: "ignores path-escaping entry names",
			entries: map[string]string{
				"../bino":     "evil",
				"sub/bino":    "nested",
				"bino.backup": "other",
			},
			wantErr: "bino binary not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			archive := writeTarGz(t, tt.entries)
			var out bytes.Buffer

			err := extractBinaryFromTarGz(bytes.NewReader(archive), &out)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("extractBinaryFromTarGz() should error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("error = %v, want %s", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("extractBinaryFromTarGz() error = %v", err)
			}
			if out.String() != tt.want {
				t.Errorf("extracted content = %q, want %q", out.String(), tt.want)
			}
		})
	}

	t.Run("invalid gzip errors", func(t *testing.T) {
		err := extractBinaryFromTarGz(strings.NewReader("not gzip"), &bytes.Buffer{})
		if err == nil {
			t.Fatal("extractBinaryFromTarGz() should error on invalid gzip")
		}
		if !strings.Contains(err.Error(), "gzip") {
			t.Errorf("error = %v, want gzip", err)
		}
	})
}

func TestExtractBinaryFromZip(t *testing.T) {
	tests := []struct {
		name    string
		entries map[string]string
		want    string
		wantErr string
	}{
		{
			name:    "extracts bino.exe",
			entries: map[string]string{"duckdb.dll": "dll", "bino.exe": "exe-content"},
			want:    "exe-content",
		},
		{
			name:    "extracts bino",
			entries: map[string]string{"bino": "binary-content"},
			want:    "binary-content",
		},
		{
			name:    "binary missing",
			entries: map[string]string{"README.md": "docs"},
			wantErr: "bino binary not found",
		},
		{
			name: "ignores path-escaping entry names",
			entries: map[string]string{
				"../bino":      "evil",
				`..\bino.exe`:  "evil-windows",
				"sub/bino.exe": "nested",
			},
			wantErr: "bino binary not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			zipPath := filepath.Join(t.TempDir(), "archive.zip")
			writeTestZip(t, zipPath, tt.entries)
			var out bytes.Buffer

			err := extractBinaryFromZip(zipPath, &out)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("extractBinaryFromZip() should error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("error = %v, want %s", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("extractBinaryFromZip() error = %v", err)
			}
			if out.String() != tt.want {
				t.Errorf("extracted content = %q, want %q", out.String(), tt.want)
			}
		})
	}

	t.Run("invalid archive errors", func(t *testing.T) {
		zipPath := filepath.Join(t.TempDir(), "bad.zip")
		if err := os.WriteFile(zipPath, []byte("not a zip"), 0o644); err != nil {
			t.Fatalf("write bad zip: %v", err)
		}
		if err := extractBinaryFromZip(zipPath, &bytes.Buffer{}); err == nil {
			t.Error("extractBinaryFromZip() should error on invalid archive")
		}
	})
}

func TestExtractDLLFromZip(t *testing.T) {
	t.Run("extracts duckdb.dll into target dir", func(t *testing.T) {
		tmp := t.TempDir()
		zipPath := filepath.Join(tmp, "archive.zip")
		writeTestZip(t, zipPath, map[string]string{
			"bino.exe":   "exe",
			"duckdb.dll": "dll-content",
		})

		targetDir := filepath.Join(tmp, "install")
		if err := os.MkdirAll(targetDir, 0o755); err != nil {
			t.Fatalf("mkdir target: %v", err)
		}
		if err := extractDLLFromZip(zipPath, targetDir); err != nil {
			t.Fatalf("extractDLLFromZip() error = %v", err)
		}

		data, err := os.ReadFile(filepath.Join(targetDir, "duckdb.dll"))
		if err != nil {
			t.Fatalf("read extracted dll: %v", err)
		}
		if string(data) != "dll-content" {
			t.Errorf("dll content = %q, want %q", data, "dll-content")
		}
	})

	t.Run("missing dll is not an error", func(t *testing.T) {
		tmp := t.TempDir()
		zipPath := filepath.Join(tmp, "archive.zip")
		writeTestZip(t, zipPath, map[string]string{"bino.exe": "exe"})

		if err := extractDLLFromZip(zipPath, tmp); err != nil {
			t.Fatalf("extractDLLFromZip() error = %v", err)
		}
		if _, err := os.Stat(filepath.Join(tmp, "duckdb.dll")); !os.IsNotExist(err) {
			t.Error("duckdb.dll should not exist")
		}
	})

	t.Run("ignores path-escaping dll entries", func(t *testing.T) {
		tmp := t.TempDir()
		zipPath := filepath.Join(tmp, "archive.zip")
		writeTestZip(t, zipPath, map[string]string{
			"../duckdb.dll": "evil",
		})

		targetDir := filepath.Join(tmp, "install")
		if err := os.MkdirAll(targetDir, 0o755); err != nil {
			t.Fatalf("mkdir target: %v", err)
		}
		if err := extractDLLFromZip(zipPath, targetDir); err != nil {
			t.Fatalf("extractDLLFromZip() error = %v", err)
		}

		// The escaping entry must not be written anywhere: neither inside the
		// target directory nor as a sibling of it.
		if _, err := os.Stat(filepath.Join(targetDir, "duckdb.dll")); !os.IsNotExist(err) {
			t.Error("escaping entry was extracted into target dir")
		}
		if _, err := os.Stat(filepath.Join(tmp, "duckdb.dll")); !os.IsNotExist(err) {
			t.Error("escaping entry escaped the target dir")
		}
	})

	t.Run("invalid archive errors", func(t *testing.T) {
		tmp := t.TempDir()
		zipPath := filepath.Join(tmp, "bad.zip")
		if err := os.WriteFile(zipPath, []byte("not a zip"), 0o644); err != nil {
			t.Fatalf("write bad zip: %v", err)
		}
		if err := extractDLLFromZip(zipPath, tmp); err == nil {
			t.Error("extractDLLFromZip() should error on invalid archive")
		}
	})
}

func TestGetAssetName(t *testing.T) {
	name := getAssetName()

	if !strings.HasPrefix(name, "bino-cli_") {
		t.Errorf("asset name %q should start with bino-cli_", name)
	}
	wantExt := ".tar.gz"
	if runtime.GOOS == "windows" {
		wantExt = ".zip"
	}
	if !strings.HasSuffix(name, wantExt) {
		t.Errorf("asset name %q should end with %s", name, wantExt)
	}
	if runtime.GOARCH == "amd64" && !strings.Contains(name, "x86_64") {
		t.Errorf("asset name %q should map amd64 to x86_64", name)
	}
}

func TestResolveLatestVersion(t *testing.T) {
	tests := []struct {
		name        string
		handler     http.HandlerFunc
		wantVersion string
		wantErr     string
	}{
		{
			name: "extracts version from redirect",
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Location", "/download/v1.2.3/"+getAssetName())
				w.WriteHeader(http.StatusFound)
			},
			wantVersion: "v1.2.3",
		},
		{
			name: "non-redirect status errors",
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(http.StatusOK)
			},
			wantErr: "unexpected status code",
		},
		{
			name: "redirect without version errors",
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Location", "/somewhere/else")
				w.WriteHeader(http.StatusFound)
			},
			wantErr: "could not extract version",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			srv := httptest.NewServer(tt.handler)
			defer srv.Close()
			setBaseURL(t, srv.URL)

			gotVersion, gotURL, err := resolveLatestVersion(context.Background())
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("resolveLatestVersion() should error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("error = %v, want %s", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("resolveLatestVersion() error = %v", err)
			}
			if gotVersion != tt.wantVersion {
				t.Errorf("version = %q, want %q", gotVersion, tt.wantVersion)
			}
			if !strings.Contains(gotURL, "/download/"+tt.wantVersion+"/") {
				t.Errorf("download URL = %q, want it to contain /download/%s/", gotURL, tt.wantVersion)
			}
		})
	}
}

func TestFetchExpectedChecksum(t *testing.T) {
	validSum := strings.Repeat("12", 32)
	assetName := getAssetName()

	tests := []struct {
		name    string
		handler http.HandlerFunc
		want    string
		wantErr string
	}{
		{
			name: "returns checksum for asset",
			handler: func(w http.ResponseWriter, r *http.Request) {
				if r.URL.Path != "/download/v1.2.3/checksums.txt" {
					http.NotFound(w, r)
					return
				}
				fmt.Fprintf(w, "%s  other-asset.tar.gz\n%s  %s\n", strings.Repeat("ef", 32), validSum, assetName)
			},
			want: validSum,
		},
		{
			name: "asset not listed",
			handler: func(w http.ResponseWriter, r *http.Request) {
				fmt.Fprintf(w, "%s  other-asset.tar.gz\n", validSum)
			},
			wantErr: "no checksum found",
		},
		{
			name:    "missing checksums file",
			handler: http.NotFound,
			wantErr: "checksums.txt not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			srv := httptest.NewServer(tt.handler)
			defer srv.Close()
			setBaseURL(t, srv.URL)

			got, err := fetchExpectedChecksum(context.Background(), "v1.2.3", assetName)
			if tt.wantErr != "" {
				if err == nil {
					t.Fatal("fetchExpectedChecksum() should error")
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Errorf("error = %v, want %s", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("fetchExpectedChecksum() error = %v", err)
			}
			if got != tt.want {
				t.Errorf("checksum = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestCheckForUpdate(t *testing.T) {
	t.Run("skips check within 24h interval", func(t *testing.T) {
		t.Setenv("HOME", t.TempDir())
		if err := SaveState(&State{LastUpdateCheck: time.Now()}); err != nil {
			t.Fatalf("SaveState() error = %v", err)
		}

		hits := 0
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			hits++
		}))
		defer srv.Close()
		setBaseURL(t, srv.URL)

		result, err := CheckForUpdate(context.Background())
		if err != nil {
			t.Fatalf("CheckForUpdate() error = %v", err)
		}
		if result != nil {
			t.Errorf("CheckForUpdate() = %+v, want nil", result)
		}
		if hits != 0 {
			t.Errorf("server was hit %d times, want 0", hits)
		}
	})

	t.Run("reports newer version", func(t *testing.T) {
		t.Setenv("HOME", t.TempDir())
		setVersion(t, "1.0.0")

		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Location", "/download/v2.0.0/"+getAssetName())
			w.WriteHeader(http.StatusFound)
		}))
		defer srv.Close()
		setBaseURL(t, srv.URL)

		result, err := CheckForUpdate(context.Background())
		if err != nil {
			t.Fatalf("CheckForUpdate() error = %v", err)
		}
		if result == nil {
			t.Fatal("CheckForUpdate() = nil, want update result")
		}
		if result.LatestVersion != "v2.0.0" {
			t.Errorf("LatestVersion = %q, want v2.0.0", result.LatestVersion)
		}
		if result.CurrentVersion != "1.0.0" {
			t.Errorf("CurrentVersion = %q, want 1.0.0", result.CurrentVersion)
		}

		// The check time must be persisted for the 24h interval.
		state, err := LoadState()
		if err != nil {
			t.Fatalf("LoadState() error = %v", err)
		}
		if state.LastUpdateCheck.IsZero() {
			t.Error("LastUpdateCheck was not persisted")
		}
	})

	t.Run("returns nil when up to date", func(t *testing.T) {
		t.Setenv("HOME", t.TempDir())
		setVersion(t, "2.0.0")

		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Location", "/download/v2.0.0/"+getAssetName())
			w.WriteHeader(http.StatusFound)
		}))
		defer srv.Close()
		setBaseURL(t, srv.URL)

		result, err := CheckForUpdate(context.Background())
		if err != nil {
			t.Fatalf("CheckForUpdate() error = %v", err)
		}
		if result != nil {
			t.Errorf("CheckForUpdate() = %+v, want nil", result)
		}
	})
}

func TestUpdate(t *testing.T) {
	t.Run("already up to date returns nil without download", func(t *testing.T) {
		setVersion(t, "2.0.0")

		downloads := 0
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method == http.MethodGet {
				downloads++
			}
			w.Header().Set("Location", "/download/v1.0.0/"+getAssetName())
			w.WriteHeader(http.StatusFound)
		}))
		defer srv.Close()
		setBaseURL(t, srv.URL)

		result, err := Update(context.Background(), nil)
		if err != nil {
			t.Fatalf("Update() error = %v", err)
		}
		if result != nil {
			t.Errorf("Update() = %+v, want nil", result)
		}
		if downloads != 0 {
			t.Errorf("downloads = %d, want 0", downloads)
		}
	})

	t.Run("checksum mismatch aborts update", func(t *testing.T) {
		setVersion(t, "1.0.0")

		assetName := getAssetName()
		archive := writePlatformArchive(t, map[string]string{"bino": "new-binary"})
		wrongSum := strings.Repeat("00", 32)

		var serverURL string
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			switch {
			case strings.HasSuffix(r.URL.Path, "/latest/download/"+assetName):
				w.Header().Set("Location", serverURL+"/download/v2.0.0/"+assetName)
				w.WriteHeader(http.StatusFound)
			case strings.HasSuffix(r.URL.Path, "/checksums.txt"):
				fmt.Fprintf(w, "%s  %s\n", wrongSum, assetName)
			case strings.HasSuffix(r.URL.Path, "/download/v2.0.0/"+assetName):
				_, _ = w.Write(archive)
			default:
				http.NotFound(w, r)
			}
		}))
		serverURL = srv.URL
		defer srv.Close()
		setBaseURL(t, srv.URL)

		var progress []string
		_, err := Update(context.Background(), func(msg string) { progress = append(progress, msg) })
		if err == nil {
			t.Fatal("Update() should fail on checksum mismatch")
		}
		if !strings.Contains(err.Error(), "checksum mismatch") {
			t.Errorf("error = %v, want checksum mismatch", err)
		}
		if len(progress) == 0 {
			t.Error("progress callback was never invoked")
		}
	})

	t.Run("matching checksum passes verification", func(t *testing.T) {
		setVersion(t, "1.0.0")

		assetName := getAssetName()
		// Archive deliberately lacks the binary so the update aborts at the
		// extraction step — after checksum verification but before the test
		// binary would be replaced.
		archive := writePlatformArchive(t, map[string]string{"README.md": "no binary"})
		sum := sha256.Sum256(archive)
		goodSum := hex.EncodeToString(sum[:])

		var serverURL string
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			switch {
			case strings.HasSuffix(r.URL.Path, "/latest/download/"+assetName):
				w.Header().Set("Location", serverURL+"/download/v2.0.0/"+assetName)
				w.WriteHeader(http.StatusFound)
			case strings.HasSuffix(r.URL.Path, "/checksums.txt"):
				fmt.Fprintf(w, "%s  %s\n", goodSum, assetName)
			case strings.HasSuffix(r.URL.Path, "/download/v2.0.0/"+assetName):
				_, _ = w.Write(archive)
			default:
				http.NotFound(w, r)
			}
		}))
		serverURL = srv.URL
		defer srv.Close()
		setBaseURL(t, srv.URL)

		_, err := Update(context.Background(), nil)
		if err == nil {
			t.Fatal("Update() should fail at extraction")
		}
		if strings.Contains(err.Error(), "checksum mismatch") {
			t.Errorf("Update() failed checksum verification: %v", err)
		}
		if !strings.Contains(err.Error(), "bino binary not found") {
			t.Errorf("error = %v, want bino binary not found", err)
		}
	})
}
