package template

import (
	"bytes"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"testing/fstest"
)

// minimalGoldenData mirrors the values `bino init -y` derives for the default
// answers, with the non-deterministic vars (.ReportID/.Date/.EngineVersion)
// pinned so the output can be compared against committed golden files.
func minimalGoldenData() map[string]any {
	return map[string]any{
		"ReportName":     "rainbow-sample-report",
		"ReportTitle":    "Rainbow Sample Report",
		"Language":       "en",
		"Filename":       "rainbow-sample-report.pdf",
		"LayoutName":     "rainbow-sample-report-page",
		"DataSourceName": "rainbow_sample_report_data",
		"DataSetName":    "rainbow_sample_report_dataset",
		"ReportID":       "00000000-0000-0000-0000-000000000000",
		"EngineVersion":  "v1.0.0-alpha.15",
		"Date":           "2026-01-01T00:00:00Z",
		"BinoVersion":    "0.0.0-test",
		// [package] vars; only the predef template references them.
		"PackageName":        "@acme/rainbow-sample-report",
		"PackageDescription": "A reusable kit.",
		"PackageVisibility":  "private",
		"PackageTags":        []string{"starter", "ibcs"},
		"PackageCategory":    "components",
	}
}

// TestRenderMinimalByteStable is the byte-stability gate: rendering the built-in
// minimal template with fixed inputs must reproduce the historical fmt.Sprintf
// scaffold exactly, file for file.
func TestRenderMinimalByteStable(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}

	dest := t.TempDir()
	created, err := RenderTree(root, manifest, dest, minimalGoldenData(), false)
	if err != nil {
		t.Fatal(err)
	}

	want := []string{".bnignore", ".gitignore", "bino.toml", "data.yaml", "pages.yaml", "report.yaml"}
	if !reflect.DeepEqual(created, want) {
		t.Fatalf("created files = %v, want %v", created, want)
	}

	for _, rel := range created {
		got, err := os.ReadFile(filepath.Join(dest, rel))
		if err != nil {
			t.Fatalf("read rendered %s: %v", rel, err)
		}
		golden, err := os.ReadFile(filepath.Join("testdata", "golden", "minimal", rel))
		if err != nil {
			t.Fatalf("read golden %s: %v", rel, err)
		}
		if !bytes.Equal(got, golden) {
			t.Errorf("%s mismatch:\n--- got ---\n%s\n--- want ---\n%s", rel, got, golden)
		}
	}
}

// TestRenderMinimalNoEngineVersion verifies the conditional engine-version line:
// with no local engine, bino.toml ends right after report-id, matching the old
// best-effort behavior.
func TestRenderMinimalNoEngineVersion(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}

	data := minimalGoldenData()
	data["EngineVersion"] = ""

	dest := t.TempDir()
	if _, err := RenderTree(root, manifest, dest, data, false); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dest, "bino.toml"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# Bino project configuration\n" +
		"# This file marks the root of a bino reporting project.\n" +
		"# Generated by 'bino init' on 2026-01-01T00:00:00Z\n\n" +
		"report-id = \"00000000-0000-0000-0000-000000000000\"\n"
	if string(got) != want {
		t.Errorf("bino.toml without engine version:\n--- got ---\n%q\n--- want ---\n%q", got, want)
	}
}

// standardFiles is the exact file set the standard template scaffolds, in the
// sorted order RenderTree returns. The scaffold is a user-visible contract, so a
// change here should be a deliberate edit, not a silent drift.
var standardFiles = []string{
	".bnignore",
	".gitignore",
	"LICENSE",
	"README.md",
	"bino.toml",
	"components/example_chart.yaml",
	"datasets/revenue_by_city.yaml",
	"datasets/sample.yaml",
	"datasources/data.yaml",
	"datasources/new_cities.yaml",
	"docs/01_example.md",
	// Path-templated: i18n/{{ .Language }}.yaml. The fixture renders "en", so
	// this entry is also the proof that renderPath fired.
	"i18n/en.yaml",
	"pages/pages.yaml",
	"reports/document.yaml",
	"reports/live.yaml",
	"reports/report.yaml",
	"resources/assets/logos/image.png",
	"resources/assets/logos/logo.yaml",
	"resources/assets/pictograms/flags/1x1/au.svg",
	"resources/assets/pictograms/flags/1x1/cn.svg",
	"resources/assets/pictograms/flags/1x1/de.svg",
	"resources/assets/pictograms/flags/1x1/fr.svg",
	"resources/assets/pictograms/flags/1x1/jp.svg",
	"resources/assets/pictograms/flags/1x1/us.svg",
	"resources/assets/pictograms/flags/INFO",
	"resources/assets/pictograms/flags/LICENSE",
	"resources/assets/pictograms/flags/flags.yaml",
	"resources/data/new_cities.csv",
	"resources/signing/example_cert.pem",
	"resources/signing/example_key.pem",
	"resources/sql/example.sql",
	"scripts/log_hook.sh",
	"styles/corporate_design_extern.yaml",
}

// renderStandard renders the built-in standard template into a temp dir with the
// pinned fixture values, returning the created paths and the destination.
func renderStandard(t *testing.T) ([]string, string) {
	t.Helper()
	root, err := BuiltinRoot("standard")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("standard")
	if err != nil {
		t.Fatal(err)
	}
	dest := t.TempDir()
	created, err := RenderTree(root, manifest, dest, minimalGoldenData(), false)
	if err != nil {
		t.Fatal(err)
	}
	return created, dest
}

// TestRenderStandardFoldered verifies the standard template scaffolds the full
// reference bundle into canonical folders and renders without error.
func TestRenderStandardFoldered(t *testing.T) {
	created, _ := renderStandard(t)
	if !reflect.DeepEqual(created, standardFiles) {
		t.Fatalf("created files = %v, want %v", created, standardFiles)
	}
}

// TestRenderStandardLeavesNoActions guards the substitution itself: a rendered
// bundle must contain no unresolved template action and no "<no value>" from a
// variable that silently went missing.
func TestRenderStandardLeavesNoActions(t *testing.T) {
	created, dest := renderStandard(t)
	binary := map[string]bool{".png": true, ".svg": true, ".csv": true}
	for _, rel := range created {
		if binary[filepath.Ext(rel)] {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dest, filepath.FromSlash(rel)))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		for _, marker := range []string{"{{", "<no value>"} {
			if bytes.Contains(body, []byte(marker)) {
				t.Errorf("%s contains unrendered %q", rel, marker)
			}
		}
	}
}

// predefFiles is the exact file set the predef template scaffolds, in the
// sorted order RenderTree returns. Like standardFiles this is a user-visible
// contract; mocks/ is deliberately part of it and deliberately not a canonical
// manifest folder.
var predefFiles = []string{
	".bnignore",
	".gitignore",
	"README.md",
	"bino.toml",
	"components/revenue_table.yaml",
	"mocks/mock_data.yaml",
	"mocks/preview.yaml",
	"resources/logo.png",
	"resources/logo.yaml",
	"styles/corporate_theme.yaml",
}

// renderPredef renders the built-in predef template into a temp dir with the
// pinned fixture values, returning the created paths and the destination.
func renderPredef(t *testing.T) ([]string, string) {
	t.Helper()
	root, err := BuiltinRoot("predef")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("predef")
	if err != nil {
		t.Fatal(err)
	}
	dest := t.TempDir()
	created, err := RenderTree(root, manifest, dest, minimalGoldenData(), false)
	if err != nil {
		t.Fatal(err)
	}
	return created, dest
}

// TestRenderPredefFoldered verifies the predef template scaffolds the package
// tree plus its mocks/ preview harness and renders without error.
func TestRenderPredefFoldered(t *testing.T) {
	created, _ := renderPredef(t)
	if !reflect.DeepEqual(created, predefFiles) {
		t.Fatalf("created files = %v, want %v", created, predefFiles)
	}
}

// TestRenderPredefLeavesNoActions guards the substitution: the scaffold must
// contain no unresolved template action and no "<no value>" from a variable
// that silently went missing.
func TestRenderPredefLeavesNoActions(t *testing.T) {
	created, dest := renderPredef(t)
	for _, rel := range created {
		if filepath.Ext(rel) == ".png" {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dest, filepath.FromSlash(rel)))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		for _, marker := range []string{"{{", "<no value>"} {
			if bytes.Contains(body, []byte(marker)) {
				t.Errorf("%s contains unrendered %q", rel, marker)
			}
		}
	}
}

// TestBuiltinEmbedHasNoJunk fails if editor or OS droppings ever reach the
// embedded tree. `//go:embed all:builtin` takes dotfiles, and .DS_Store is
// gitignored rather than impossible — a local build would otherwise ship one
// into every scaffolded project.
func TestBuiltinEmbedHasNoJunk(t *testing.T) {
	junk := map[string]bool{".DS_Store": true, "Thumbs.db": true, ".gitkeep": true}
	err := fs.WalkDir(builtinFS, "builtin", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if junk[path.Base(p)] {
			t.Errorf("embedded junk file %s", p)
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if info.Size() == 0 {
			t.Errorf("embedded zero-byte file %s", p)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

// TestRenderTreeRejectsPathTraversal ensures a rendered path that escapes the
// destination (e.g. via a "../" field value) is refused.
func TestRenderTreeRejectsPathTraversal(t *testing.T) {
	src := fstest.MapFS{
		"{{ .Name }}.txt": &fstest.MapFile{Data: []byte("x")},
	}
	manifest := &ProjectTemplate{}
	dest := filepath.Join(t.TempDir(), "out")
	_, err := RenderTree(src, manifest, dest, map[string]any{"Name": "../escape"}, false)
	if err == nil || !strings.Contains(err.Error(), "escapes the target directory") {
		t.Fatalf("expected path-traversal rejection, got %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(filepath.Dir(dest), "escape.txt")); !os.IsNotExist(statErr) {
		t.Errorf("escape file should not have been written")
	}
}

// TestRenderMissingKeyErrors confirms a referenced-but-absent variable fails
// loudly instead of emitting "<no value>".
func TestRenderMissingKeyErrors(t *testing.T) {
	_, err := Render("t", []byte("name: {{ .Missing }}\n"), map[string]any{})
	if err == nil {
		t.Fatal("expected error for missing key, got nil")
	}
}

// TestRenderForceOverwrite confirms force lets a re-render overwrite existing
// files while the default path refuses.
func TestRenderForceOverwrite(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}
	dest := t.TempDir()
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), false); err != nil {
		t.Fatal(err)
	}
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), false); err == nil {
		t.Fatal("expected error re-rendering without force")
	}
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), true); err != nil {
		t.Fatalf("force re-render failed: %v", err)
	}
}
