package template

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"testing/fstest"
)

// minimalGoldenData mirrors the values `bino init -y` derives for the default
// answers, with the non-deterministic vars (.ReportID/.Date/.EngineVersion)
// pinned so the output can be compared against committed golden files.
func minimalGoldenData() map[string]any {
	return map[string]any{
		"ReportName":     "rainbow-sample-report",
		"ReportTitle":    "Rainbow Sample Report",
		"Language":       "en",
		"Filename":       "rainbow-sample-report.pdf",
		"LayoutName":     "rainbow-sample-report-page",
		"DataSourceName": "rainbow_sample_report_data",
		"ReportID":       "00000000-0000-0000-0000-000000000000",
		"EngineVersion":  "v1.0.0-alpha.15",
		"Date":           "2026-01-01T00:00:00Z",
		"BinoVersion":    "0.0.0-test",
	}
}

// TestRenderMinimalByteStable is the byte-stability gate: rendering the built-in
// minimal template with fixed inputs must reproduce the historical fmt.Sprintf
// scaffold exactly, file for file.
func TestRenderMinimalByteStable(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}

	dest := t.TempDir()
	created, err := RenderTree(root, manifest, dest, minimalGoldenData(), false)
	if err != nil {
		t.Fatal(err)
	}

	want := []string{".bnignore", ".gitignore", "bino.toml", "data.yaml", "pages.yaml", "report.yaml"}
	if !reflect.DeepEqual(created, want) {
		t.Fatalf("created files = %v, want %v", created, want)
	}

	for _, rel := range created {
		got, err := os.ReadFile(filepath.Join(dest, rel))
		if err != nil {
			t.Fatalf("read rendered %s: %v", rel, err)
		}
		golden, err := os.ReadFile(filepath.Join("testdata", "golden", "minimal", rel))
		if err != nil {
			t.Fatalf("read golden %s: %v", rel, err)
		}
		if !bytes.Equal(got, golden) {
			t.Errorf("%s mismatch:\n--- got ---\n%s\n--- want ---\n%s", rel, got, golden)
		}
	}
}

// TestRenderMinimalNoEngineVersion verifies the conditional engine-version line:
// with no local engine, bino.toml ends right after report-id, matching the old
// best-effort behavior.
func TestRenderMinimalNoEngineVersion(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}

	data := minimalGoldenData()
	data["EngineVersion"] = ""

	dest := t.TempDir()
	if _, err := RenderTree(root, manifest, dest, data, false); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dest, "bino.toml"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# Bino project configuration\n" +
		"# This file marks the root of a bino reporting project.\n" +
		"# Generated by 'bino init' on 2026-01-01T00:00:00Z\n\n" +
		"report-id = \"00000000-0000-0000-0000-000000000000\"\n"
	if string(got) != want {
		t.Errorf("bino.toml without engine version:\n--- got ---\n%q\n--- want ---\n%q", got, want)
	}
}

// TestRenderStandardFoldered verifies the standard template scaffolds into
// canonical folders and renders without error.
func TestRenderStandardFoldered(t *testing.T) {
	root, err := BuiltinRoot("standard")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("standard")
	if err != nil {
		t.Fatal(err)
	}

	dest := t.TempDir()
	created, err := RenderTree(root, manifest, dest, minimalGoldenData(), false)
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		".bnignore",
		".gitignore",
		"bino.toml",
		filepath.Join("datasources", "data.yaml"),
		filepath.Join("pages", "home.yaml"),
		filepath.Join("reports", "report.yaml"),
	}
	if !reflect.DeepEqual(created, want) {
		t.Fatalf("created files = %v, want %v", created, want)
	}
}

// TestRenderTreeRejectsPathTraversal ensures a rendered path that escapes the
// destination (e.g. via a "../" field value) is refused.
func TestRenderTreeRejectsPathTraversal(t *testing.T) {
	src := fstest.MapFS{
		"{{ .Name }}.txt": &fstest.MapFile{Data: []byte("x")},
	}
	manifest := &ProjectTemplate{}
	dest := filepath.Join(t.TempDir(), "out")
	_, err := RenderTree(src, manifest, dest, map[string]any{"Name": "../escape"}, false)
	if err == nil || !strings.Contains(err.Error(), "escapes the target directory") {
		t.Fatalf("expected path-traversal rejection, got %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(filepath.Dir(dest), "escape.txt")); !os.IsNotExist(statErr) {
		t.Errorf("escape file should not have been written")
	}
}

// TestRenderMissingKeyErrors confirms a referenced-but-absent variable fails
// loudly instead of emitting "<no value>".
func TestRenderMissingKeyErrors(t *testing.T) {
	_, err := Render("t", []byte("name: {{ .Missing }}\n"), map[string]any{})
	if err == nil {
		t.Fatal("expected error for missing key, got nil")
	}
}

// TestRenderForceOverwrite confirms force lets a re-render overwrite existing
// files while the default path refuses.
func TestRenderForceOverwrite(t *testing.T) {
	root, err := BuiltinRoot("minimal")
	if err != nil {
		t.Fatal(err)
	}
	manifest, err := BuiltinManifest("minimal")
	if err != nil {
		t.Fatal(err)
	}
	dest := t.TempDir()
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), false); err != nil {
		t.Fatal(err)
	}
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), false); err == nil {
		t.Fatal("expected error re-rendering without force")
	}
	if _, err := RenderTree(root, manifest, dest, minimalGoldenData(), true); err != nil {
		t.Fatalf("force re-render failed: %v", err)
	}
}
